### ISSUE TITLE
raup_crick_abundance.R报错

### ISSUE THREAD

**Issue by liaochenlanruo** [jianshu93/Fungi_BioDiv_CommAssembly#1]
请问69和74行的distance()函数哪里来的，没见调用哪个package，报错如下：

Error in distance(null.spXsite, method = "bray-curtis") :
  could not find function "distance"
Calls: raup_crick_abundance
Execution halted

**Comment by liaochenlanruo** [comment]
应该是“ecodist”包

**Comment by jianshu93** [comment]
Thank you! Yes you are right. Thanks for correction. I will update it.

Jianshu
